#!/bin/bash




#####
#
#  This file is still in the test stage @todo
#
#
#####



#Get new sitename
SITENAME=$1;
SITEPATH=$2;
SITEBACKUP=$3;


DIRPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DATE=`date +%Y-%m-%d-%H-%M-%S`

cd $SITEBACKUP;
echo $SITEPATH
echo $SITEBACKUP$DATE-$SITENAME.tar.gz
tar -zcvf $DATE-$SITENAME.tar.gz  --exclude='.git' --exclude='sites/default' -C $SITEPATH .
cd $DIRPATH;
