#!/bin/bash



#####
#
#  This file is still in the test stage @todo
#
#
#####


#Get new sitename
SITENAME=$1;
USERNAME=$2;
PASSWORD=$3;
SITEPATH=$4;

DIRPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DATE=`date +%Y-%m-%d-%H-%M-%S`

cd $SITEPATH;

/usr/bin/mysqldump -u $USERNAME -p"$PASSWORD" $SITENAME | gzip > "$SITEPATH$DATE-$SITENAME.sql"
echo $SITEPATH$DATE-$SITENAME.sql;
echo $SITEPATH$DATE-$SITENAME.sql.gz;
gzip -c "$SITEPATH$DATE-$SITENAME.sql" > "$SITEPATH$DATE-$SITENAME.sql.gz"

cd $DIRPATH;
