#!/bin/bash
# Directory Path

##
# Build System
##

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"


WEBSITESPATH=$1;
MKNEWDIR=$2;
DIRECTORY=$WEBSITESPATH/$MKNEWDIR;
DRUSHMAKEFILE='.makefile';

##
#  Making directory structure for build
##
while true
do
  if [ -d "$DIRECTORY" ]; then
     dirAdd=$(($dirAdd+1));
     DIRECTORY=$DIRECTORY$dirAdd;
   fi
   if [ ! -d "$DIRECTORY" ] ; then
        echo "create";
        echo $DIRECTORY;
        mkdir $DIRECTORY;
        mkdir $DIRECTORY/'build';
        mkdir $DIRECTORY/'features';
        mkdir $DIRECTORY/'images';
        mkdir $DIRECTORY/'documents';
        mkdir $DIRECTORY/'databases';
        mkdir $DIRECTORY/'databases/testing';
        mkdir $DIRECTORY/'databases/production';
        mkdir $DIRECTORY/'backup-build';

        BUILDPATH=$DIRECTORY/'build';
        echo $BUILDPATH;
     break;
  fi
done

###
#  Test to see if path exists
###
if [ -d "$BUILDPATH" ]; then

  ###
  #  git clone and make file
  ###
  git clone https://github.com/purencool/make.git $BUILDPATH
  cd $BUILDPATH;
  $DRUSHPATH/drush make $DRUSHMAKEFILE -y
  echo $DRUSHPATH;

  ##
  # If you need certain permissions or own settings on the 
  # directory. By default it will work use the web server
  ##
  if [ -n "$CHOWNER" ]; then
     chown -Rf $CHOWNER $DIRECTORY
  fi
  if [ -n "$PERMISSIONS" ]; then
    chmod -Rf $PERMISSIONS $DIRECTORY
  fi
fi
