#!/bin/bash
# Directory Path

##
# Build System
##

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"


WEBSITESPATH=$1;
MKNEWDIR=$2;
DIRECTORY=$WEBSITESPATH/$MKNEWDIR;
DRUSHMAKEFILE='.make.yml';

###
#  TESTING AND ADDING BUILD PATH
###
while true
do
  if [ -d "$DIRECTORY" ]; then
     dirAdd=$(($dirAdd+1));
     DIRECTORY=$DIRECTORY$dirAdd;
   fi
   if [ ! -d "$DIRECTORY" ] ; then
        echo "create";
        echo $DIRECTORY;
        mkdir $DIRECTORY;
        mkdir $DIRECTORY/'features';
        mkdir $DIRECTORY/'images';
        mkdir $DIRECTORY/'documents';
        mkdir $DIRECTORY/'databases';
        mkdir $DIRECTORY/'databases/testing';
        mkdir $DIRECTORY/'databases/production';
        mkdir $DIRECTORY/'backup-build';

        echo $DIRECTORY;
     break;
  fi
done

###
#
#  TESTING TO SEE IF BUILD PATH EXISTS
#
###
if [ -d "$DIRECTORY" ]; then
  ###
  #  git clone and make file
  ###
  DIRBUILD=$DIRECTORY'/build';
  #echo $DIRBUILD;
  git clone https://github.com/purencool/make.git  $DIRBUILD;
  cd $DIRBUILD;
  $DRUSHPATH/drush make $DRUSHMAKEFILE -y

  $DRUSHPATH/drush dl ds
  $DRUSHPATH/drush dl devel
  $DRUSHPATH/drush dl honeypot

  #$DRUSHPATH/drush dl omega

  cd ./modules
  ###
  # Git clone until I can get the Drush make to work
  ###
  git clone --branch 8.x-3.x http://git.drupal.org/sandbox/grayside/2120935.git features
  git clone --branch d8panels http://git.drupal.org/sandbox/dsnopek/2290237.git d8panels
  git clone  https://github.com/geberele/D8-Example-Module.git
  git clone --branch 8.x-1.x http://git.drupal.org/project/adminimal_theme.git
  git clone --branch 8.x-1.x http://git.drupal.org/project/coffee.git
  git clone --branch 8.x-1.x http://git.drupal.org/project/examples.git

  cd ../themes
  git clone --branch 8.x-5.x http://git.drupal.org/project/omega.git
  
  ##
  # If you need certain permissions or own settings on the 
  # directory. By default it will work use the web server
  ##
  if [ -n "$CHOWNER" ]; then
     chown -Rf $CHOWNER $DIRECTORY
  fi
  if [ -n "$PERMISSIONS" ]; then
    chmod -Rf $PERMISSIONS $DIRECTORY
  fi
fi
