#!/bin/bash
# Directory Path

##
# Build System
##

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"


WEBSITESPATH=$1;
MKNEWDIR=$2;
DIRECTORY=$WEBSITESPATH/$MKNEWDIR;
#DIRECTORY="/var/www/html/purencool_build_tools/test_sites/test/d8";
#DRUSHMAKEFILE='.makefiled8';

###
#  TESTING AND ADDING BUILD PATH
###
while true
do
  if [ -d "$DIRECTORY" ]; then
     dirAdd=$(($dirAdd+1));
     DIRECTORY=$DIRECTORY$dirAdd;
   fi
   if [ ! -d "$DIRECTORY" ] ; then
        echo "create";
        echo $DIRECTORY;
        mkdir $DIRECTORY;
        mkdir $DIRECTORY/'features';
        mkdir $DIRECTORY/'images';
        mkdir $DIRECTORY/'documents';
        mkdir $DIRECTORY/'databases';
        mkdir $DIRECTORY/'databases/testing';
        mkdir $DIRECTORY/'databases/production';
        mkdir $DIRECTORY/'backup-build';

        echo $DIRECTORY;
     break;
  fi
done

###
#
#  TESTING TO SEE IF BUILD PATH EXISTS
#
###
if [ -d "$DIRECTORY" ]; then
  ###
  #  drush and make file
  ###
  cd $DIRECTORY;
  $DRUSHPATH/drush dl drupal-8 --destination="$DIRECTORY" --drupal-project-rename=build
  cd $DIRECTORY/'build/modules'
  $DRUSHPATH/drush dl ds
  $DRUSHPATH/drush dl devel
  $DRUSHPATH/drush dl honeypot

  git clone --branch 8.x-3.x http://git.drupal.org/sandbox/grayside/2120935.git features
  git clone --branch d8panels http://git.drupal.org/sandbox/dsnopek/2290237.git d8panels

  chown -Rf $CHOWNER $DIRECTORY
  chmod -Rf $PERMISSIONS $DIRECTORY
fi
