#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

SITEPATH=$1;
cd $SITEPATH;
compass compile
##
# Refresh browser
##
currentwindow=`xdotool getwindowfocus`
id=`xdotool search --name -- '- Google Chrome' windowactivate key --window 0 --clearmodifiers ctrl+r`
xdotool windowmap $id&>/dev/null;
xdotool windowmap $currentwindow;
xdotool windowactivate $currentwindow;

cd $DIRPATH;
