#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

THEMEPATH=$1;

cd $THEMEPATH;
compass compile
##
# Refresh browser
##
sleep 1
currentwindow=`xdotool getwindowfocus`
id=`xdotool search --name -- "$BROWSERWINDOW" windowactivate key --window 0 --clearmodifiers ctrl+r`
xdotool windowmap $id&>/dev/null;
xdotool windowmap $currentwindow;
xdotool windowactivate $currentwindow;

cd $DIRPATH;
