#!/bin/bash
# Configuration file


###
#  Global System paths
###
DRUSHPATH='/usr/bin';
RSYNC='/usr/bin';
DIRPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WEBSITESPATH="";
BROWSERWINDOW='- Google Chrome';
MD5='md5sum'; #'md5sum' for linux  #'md5'; for mac
WATCHSLEEP='2';
