#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

SITEPATH=$1;

##
# This will refresh the browser and return to ide
##
REACT=$2;

cd $SITEPATH;

##
# Clears all the caches
##
$DRUSHPATH/drush cc all

##
# Refresh browser
##

currentwindow=`xdotool getwindowfocus`
id=`xdotool search --name -- $BROWSERWINDOW windowactivate key --window 0 --clearmodifiers ctrl+r`
xdotool windowmap $id&>/dev/null;
xdotool windowmap $currentwindow;

##
# This will refresh the browser and return to ide
##
if [ -n "$REACT" ]; then
  xdotool windowactivate $currentwindow;
fi
cd $DIRPATH;
