#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

# Drush command
SITEPATH=$1;
DRUSHCOMMAND=$2;


cd $SITEPATH;

##
# drush command
##
$DRUSHPATH/drush $DRUSHCOMMAND;


cd $DIRPATH;
