#!/bin/bash
systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

REACT=$1;
SITEPATH=$2;



##
#  If path is not provided it will try to compile from current directory
##
if [[ -z "$SITEPATH" ]] ; then  
    SITEPATH="$(pwd)";
    echo "This is the current site path to be compiled "$SITEPATH;
fi



cd $SITEPATH;

##
# Clears all the caches
##
$DRUSHPATH/drush cc all


   ##
    # Refresh browser
    ##
    currentwindow=`xdotool getwindowfocus`
    id=`xdotool search --name -- "$BROWSERWINDOW" windowactivate key --window 0 --clearmodifiers ctrl+r`
    xdotool windowmap $id&>/dev/null;
    xdotool windowmap $currentwindow;

##
# This will refresh the browser and return to original window
##
if [ "$REACT"  ==  "o" ]; then
     xdotool windowactivate $currentwindow;
fi
cd $DIRPATH;
