#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

#Get new sitename
WEBSITETYPE=$1;
SITENAME=$2;
USER=$3;
PASSWORD=$4;
DATABASEUSER=$5;
DATABASEPASSWORD=$6;
SITEPATH=$7;
EMAIL=$8;


cd $SITEPATH;

##
# Installation
##
$DRUSHPATH/drush site-install -y $WEBSITETYPE --site-name=$SITENAME --account-name=$USER --account-pass=$PASSWORD --site-mail=$EMAIL  --db-url=mysql://$DATABASEUSER:$DATABASEPASSWORD@localhost/$SITENAME


##
# Development
##
$DRUSHPATH/drush en -y admin_menu
$DRUSHPATH/drush en -y coffee
$DRUSHPATH/drush en -y module_filter


##
# Disable modules
##
$DRUSHPATH/drush dis -y overlay
$DRUSHPATH/drush dis -y toolbar


##
# Structure
##
$DRUSHPATH/drush en -y features
$DRUSHPATH/drush en -y views
$DRUSHPATH/drush en -y views_ui


$DRUSHPATH/drush en -y bean
$DRUSHPATH/drush en -y bean_admin_ui
$DRUSHPATH/drush en -y bean_all
$DRUSHPATH/drush en -y bean_uuid


$DRUSHPATH/drush en -y ds
$DRUSHPATH/drush en -y ds_devel
$DRUSHPATH/drush en -y ds_extras
$DRUSHPATH/drush en -y ds_extra_layouts
$DRUSHPATH/drush en -y ds_forms
$DRUSHPATH/drush en -y ds_search
$DRUSHPATH/drush en -y ds_ui


##
# System
##
$DRUSHPATH/drush en -y backup_migrate



##
# Theme and design
##
$DRUSHPATH/drush en -y ckeditor
$DRUSHPATH/drush en -y pncmbtheme
$DRUSHPATH/drush vset theme_default pncmbtheme


cd $DIRPATH;
