#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

SITEPATH=$1;
cd $SITEPATH;


##
# Small Web Site
##
$DRUSHPATH/drush en -y pncsitedetails
$DRUSHPATH/drush en -y newsletter
$DRUSHPATH/drush en -y tagclouds
$DRUSHPATH/drush en -y easy_social

##
# Features
##
$DRUSHPATH/drush en -y pnc_user_permissions

##
# Small site with modules
##
$DRUSHPATH/drush en -y pncgoogleadd
$DRUSHPATH/drush en -y pnc_testimonials
$DRUSHPATH/drush en -y pnc_testimonials_view
$DRUSHPATH/drush en -y pncsmallwebsite


cd $DIRPATH;
