#!/bin/bash
#
# This script does the following,
# 1. Installs a web site using Drush.
# 2. Installs base modules for a basic build that is functional
#


systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"


WEBSITETYPE=$1;
SITENAME=$2;
USER=$3;
PASSWORD=$4;
DATABASEUSER=$5;
DATABASEPASSWORD=$6;
SITEPATH=$7;
EMAIL=$8;



cd $SITEPATH;

##
# Installation
##
#${SITENAME//[-._]/} removes -._
$DRUSHPATH/drush site-install -y $WEBSITETYPE --site-name=${SITENAME//[-._]/} --account-name=$USER --account-pass=$PASSWORD --site-mail=$EMAIL  --db-url=mysql://$DATABASEUSER:$DATABASEPASSWORD@localhost/$SITENAME



##
# System
##
$DRUSHPATH/drush vset -y file_public_path sites/default/files/public
$DRUSHPATH/drush vset -y file_private_path sites/default/files/private
$DRUSHPATH/drush vset -y file_temporary_path sites/default/files/tmp
$DRUSHPATH/drush en -y backup_migrate


##
# Development
##
$DRUSHPATH/drush en -y admin_menu
$DRUSHPATH/drush en -y coffee
$DRUSHPATH/drush en -y module_filter


##
# Disable modules
##
$DRUSHPATH/drush dis -y overlay
$DRUSHPATH/drush dis -y toolbar


##
# Theme and design
##
$DRUSHPATH/drush en -y ckeditor
$DRUSHPATH/drush en -y pncmbtheme
$DRUSHPATH/drush en -y jquery_update
$DRUSHPATH/drush en -y mobile_navigation
$DRUSHPATH/drush vset  theme_default pncmbtheme


##
# Content management
##
$DRUSHPATH/drush en -y insert



##
# Structure
##
$DRUSHPATH/drush en -y features
$DRUSHPATH/drush en -y views
$DRUSHPATH/drush en -y views_ui
$DRUSHPATH/drush en -y semanticviews
$DRUSHPATH/drush vdis semantic_demo
$DRUSHPATH/drush en -y bean
$DRUSHPATH/drush en -y bean_admin_ui
$DRUSHPATH/drush en -y bean_uuid
$DRUSHPATH/drush en -y block_access


##
# Purencool Modules
##
$DRUSHPATH/drush en -y pnchelp
$DRUSHPATH/drush en -y pncextras
$DRUSHPATH/drush en -y pnccopyright


cd $DIRPATH;
