#!/bin/bash

systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

SITEPATH=$1;
cd $SITEPATH;


##
# Complex Modules
##
$DRUSHPATH/drush en -y ds_devel
$DRUSHPATH/drush en -y pncsitedetails
$DRUSHPATH/drush en -y newsletter
$DRUSHPATH/drush en -y tagclouds
$DRUSHPATH/drush en -y xmlsitemap
$DRUSHPATH/drush en -y metatag
$DRUSHPATH/drush en -y page_title
$DRUSHPATH/drush en -y easy_social
# @todo This takes over the whole block system
$DRUSHPATH/drush en -y bean_all
$DRUSHPATH/drush en -y ds
$DRUSHPATH/drush en -y ds_extras
$DRUSHPATH/drush en -y ds_extra_layouts
$DRUSHPATH/drush en -y ds_forms
$DRUSHPATH/drush en -y ds_search
$DRUSHPATH/drush en -y ds_ui

##
# Features
##
$DRUSHPATH/drush en -y pnc_user_permissions




cd $DIRPATH;
