#!/bin/bash
# Directory Path

##
# Build System
##
systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"



SITEPATH=$1;

cd $SITEPATH;

$DRUSHPATH/drush pm-list --no-core --pipe --type=module --status='not installed' | awk '{print "\x27" $1 "\x27" }'

cd $DIRPATH;
