#!/bin/bash
# Directory Path

##
# Build System
##
systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"


SITEPATH=$1;

##
#  If path is not provided it will try to compile from current directory
##
if [[ -z "$SITEPATH" ]] ; then  
    SITEPATH="$(pwd)";
    echo "This is the current site path to be compiled "$SITEPATH;
fi

##
# Monitors the theme directory if there is a change
# it will compile the sass and refresh the browser
##
chsum1=""
while [[ true ]]
do
  chsum2=`find $SITEPATH -type f -exec $MD5 {} \;`
  if [[ $chsum1 != $chsum2 ]] ; then
    echo "There has been a change";

    ##
    # Compile sass
    ##
    cd $SITEPATH;
    compass compile

    ##
    # Refresh browser
    ##
    #sleep 1;
    currentwindow=`xdotool getwindowfocus`
    id=`xdotool search --name -- "$BROWSERWINDOW" windowactivate key --window 0 --clearmodifiers ctrl+r`
    xdotool windowmap $id&>/dev/null;
    xdotool windowmap $currentwindow;
    xdotool windowactivate $currentwindow;

    cd $DIRPATH;
    chsum1=$chsum2
  fi
  sleep $WATCHSLEEP;
  #echo "I have just slept";
done
