#!/bin/bash
# Directory Path

##
# Build System
##
systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

SCSSCOMP=$1;
CSSCOMP=$2;
SITEPATH=$3;


##
#  If path is not provided it will try to compile from current directory
##
if [[ -z "$SITEPATH" ]] ; then  
    SITEPATH="$(pwd)";
    echo "This is the current site path to be compiled for production "$SITEPATH;
if


##
# Compile for production
##
 if [ ! -z $SITEPATH ] ; then
    cd $SITEPATH;
                echo 'Compiling for production';
               	scss -t compressed --compass $SITEPATH'/'$SCSSCOMP $SITEPATH'/'$CSSCOMP
		echo 'Scss compile and compress  '$SCSSCOMP'  '$CSSCOMP;
    cd $DIRPATH;
fi