#!/bin/bash
# Directory Path

##
# Build System
##
systemDir=$(dirname $(readlink -f $0))
source "$systemDir/config"

SITEPATH=$1;

##
#  If path is not provided it will try to compile from current directory
##
if [[ -z "$SITEPATH" ]] ; then  
    SITEPATH="$(pwd)";
    echo "This is the current site path to be compiled for production "$SITEPATH;
fi


##
# Compile for production
##
 if [ ! -z $SITEPATH ] ; then
    cd $SITEPATH;
                echo 'Compiling for production';
                compass compile  -e production --force
    cd $DIRPATH;
fi

currentwindow=`xdotool getwindowfocus`
id=`xdotool search --name -- "$BROWSERWINDOW" windowactivate key --window 0 --clearmodifiers ctrl+r`
xdotool windowmap $id&>/dev/null;
xdotool windowmap $currentwindow;
xdotool windowactivate $currentwindow;