index:
  path: /
  defaults: { _controller: 'Trace\Controller\ApplicationController::indexAction' }

drush:
  path: /drush
  defaults: { _controller: 'Trace\Controller\DrushController::drushAction' }

base:
  path: /mywebsite
  defaults: { _controller: 'Trace\Controller\BuildAWebsiteController::authBuildNewWebsite' }
  
noinstall:
  path: /noinstall
  defaults: { _controller: 'Trace\Controller\BuildAWebsiteNoInstallController::authBuildNewWebsite' }

d7:
  path: /d7
  defaults: { _controller: 'Trace\Controller\BuildAWebsiteController7::authBuildNewWebsite' }

d8:
  path: /d8
  defaults: { _controller: 'Trace\Controller\BuildAWebsiteControllerd8::authBuildNewWebsite' }


